@Backend_HostAddress = http://localhost:5280

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Backend_HostAddress}}/tasks/
Content-Type: application/json

{
  "title": "New Task",
  "description": "Description of the new task",
  "status": "A Fazer"
}

###

GET {{Backend_HostAddress}}/tasks/
Accept: application/json

###

GET {{Backend_HostAddress}}/tasks/1
Accept: application/json

###

PUT {{Backend_HostAddress}}/tasks/1
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "Updated description",
  "status": "Em Progresso"
}

###

DELETE {{Backend_HostAddress}}/tasks/1
Accept: application/json

###